// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbvdlkfnpufqfhrptfhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpidmRsa2ZucHVmcWZocnB0Zmh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTQ2OTcsImV4cCI6MjA2MDM3MDY5N30.ouOInVDp6BggZp_SxZBIV2eAVZBvWR2w-e8cZWu78Fk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);